/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AnalyticsResponse model module.
 * @module model/AnalyticsResponse
 * @version v0
 */
export class AnalyticsResponse {
  /**
   * Constructs a new <code>AnalyticsResponse</code>.
   * @alias module:model/AnalyticsResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AnalyticsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnalyticsResponse} obj Optional instance to populate.
   * @return {module:model/AnalyticsResponse} The populated <code>AnalyticsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnalyticsResponse();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], Object);
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} status
 */
AnalyticsResponse.prototype.status = undefined;

/**
 * @member {Object} data
 */
AnalyticsResponse.prototype.data = undefined;

