/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The BalanceSheetHistoryItem model module.
 * @module model/BalanceSheetHistoryItem
 * @version v0
 */
export class BalanceSheetHistoryItem {
  /**
   * Constructs a new <code>BalanceSheetHistoryItem</code>.
   * @alias module:model/BalanceSheetHistoryItem
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BalanceSheetHistoryItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BalanceSheetHistoryItem} obj Optional instance to populate.
   * @return {module:model/BalanceSheetHistoryItem} The populated <code>BalanceSheetHistoryItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BalanceSheetHistoryItem();
      if (data.hasOwnProperty('total_asset'))
        obj.totalAsset = ApiClient.convertToType(data['total_asset'], Object);
      if (data.hasOwnProperty('total_liability'))
        obj.totalLiability = ApiClient.convertToType(data['total_liability'], Object);
      if (data.hasOwnProperty('period'))
        obj.period = ApiClient.convertToType(data['period'], Object);
    }
    return obj;
  }
}

/**
 * Total assets in the reported period
 * @member {Object} totalAsset
 */
BalanceSheetHistoryItem.prototype.totalAsset = undefined;

/**
 * Total liabilities in the reported period
 * @member {Object} totalLiability
 */
BalanceSheetHistoryItem.prototype.totalLiability = undefined;

/**
 * Reporting period
 * @member {Object} period
 */
BalanceSheetHistoryItem.prototype.period = undefined;

