/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CashFlowData} from './CashFlowData';

/**
 * The CashFlowResponse model module.
 * @module model/CashFlowResponse
 * @version v0
 */
export class CashFlowResponse {
  /**
   * Constructs a new <code>CashFlowResponse</code>.
   * @alias module:model/CashFlowResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CashFlowResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CashFlowResponse} obj Optional instance to populate.
   * @return {module:model/CashFlowResponse} The populated <code>CashFlowResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CashFlowResponse();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], Object);
      if (data.hasOwnProperty('data'))
        obj.data = CashFlowData.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {Object} status
 */
CashFlowResponse.prototype.status = undefined;

/**
 * @member {module:model/CashFlowData} data
 */
CashFlowResponse.prototype.data = undefined;

