/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SectorMarketCapAmount} from './SectorMarketCapAmount';

/**
 * The CompanyProfileData model module.
 * @module model/CompanyProfileData
 * @version v0
 */
export class CompanyProfileData {
  /**
   * Constructs a new <code>CompanyProfileData</code>.
   * @alias module:model/CompanyProfileData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CompanyProfileData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompanyProfileData} obj Optional instance to populate.
   * @return {module:model/CompanyProfileData} The populated <code>CompanyProfileData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CompanyProfileData();
      if (data.hasOwnProperty('company_profile'))
        obj.companyProfile = ApiClient.convertToType(data['company_profile'], Object);
      if (data.hasOwnProperty('sector'))
        obj.sector = ApiClient.convertToType(data['sector'], Object);
      if (data.hasOwnProperty('sector_market_cap_inr'))
        obj.sectorMarketCapInr = SectorMarketCapAmount.constructFromObject(data['sector_market_cap_inr']);
      if (data.hasOwnProperty('sector_market_cap_usd'))
        obj.sectorMarketCapUsd = SectorMarketCapAmount.constructFromObject(data['sector_market_cap_usd']);
    }
    return obj;
  }
}

/**
 * Business description of the company
 * @member {Object} companyProfile
 */
CompanyProfileData.prototype.companyProfile = undefined;

/**
 * Sector the company belongs to
 * @member {Object} sector
 */
CompanyProfileData.prototype.sector = undefined;

/**
 * Sector market capitalisation in INR
 * @member {module:model/SectorMarketCapAmount} sectorMarketCapInr
 */
CompanyProfileData.prototype.sectorMarketCapInr = undefined;

/**
 * Sector market capitalisation in USD
 * @member {module:model/SectorMarketCapAmount} sectorMarketCapUsd
 */
CompanyProfileData.prototype.sectorMarketCapUsd = undefined;

