/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CorporateActionEventDetail model module.
 * @module model/CorporateActionEventDetail
 * @version v0
 */
export class CorporateActionEventDetail {
  /**
   * Constructs a new <code>CorporateActionEventDetail</code>.
   * @alias module:model/CorporateActionEventDetail
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CorporateActionEventDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CorporateActionEventDetail} obj Optional instance to populate.
   * @return {module:model/CorporateActionEventDetail} The populated <code>CorporateActionEventDetail</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CorporateActionEventDetail();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], Object);
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], Object);
    }
    return obj;
  }
}

/**
 * Name of the event detail field
 * @member {Object} name
 */
CorporateActionEventDetail.prototype.name = undefined;

/**
 * Value of the event detail field
 * @member {Object} value
 */
CorporateActionEventDetail.prototype.value = undefined;

