/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DeliveryMargin model module.
 * @module model/DeliveryMargin
 * @version v0
 */
export class DeliveryMargin {
  /**
   * Constructs a new <code>DeliveryMargin</code>.
   * @alias module:model/DeliveryMargin
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeliveryMargin</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeliveryMargin} obj Optional instance to populate.
   * @return {module:model/DeliveryMargin} The populated <code>DeliveryMargin</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeliveryMargin();
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], Object);
      if (data.hasOwnProperty('equity'))
        obj.equity = ApiClient.convertToType(data['equity'], Object);
      if (data.hasOwnProperty('fo_settlement'))
        obj.foSettlement = ApiClient.convertToType(data['fo_settlement'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} total
 */
DeliveryMargin.prototype.total = undefined;

/**
 * @member {Object} equity
 */
DeliveryMargin.prototype.equity = undefined;

/**
 * @member {Object} foSettlement
 */
DeliveryMargin.prototype.foSettlement = undefined;

