/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The FinancialStatementEntry model module.
 * @module model/FinancialStatementEntry
 * @version v0
 */
export class FinancialStatementEntry {
  /**
   * Constructs a new <code>FinancialStatementEntry</code>.
   * @alias module:model/FinancialStatementEntry
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FinancialStatementEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FinancialStatementEntry} obj Optional instance to populate.
   * @return {module:model/FinancialStatementEntry} The populated <code>FinancialStatementEntry</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FinancialStatementEntry();
      if (data.hasOwnProperty('particular'))
        obj.particular = ApiClient.convertToType(data['particular'], Object);
      if (data.hasOwnProperty('history'))
        obj.history = ApiClient.convertToType(data['history'], Object);
    }
    return obj;
  }
}

/**
 * Type of financial statement line item
 * @member {Object} particular
 */
FinancialStatementEntry.prototype.particular = undefined;

/**
 * Historical values for this statement line item
 * @member {Object} history
 */
FinancialStatementEntry.prototype.history = undefined;

