/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {HolidayData} from './HolidayData';

/**
 * The GetHolidayResponse model module.
 * @module model/GetHolidayResponse
 * @version v0
 */
export class GetHolidayResponse {
  /**
   * Constructs a new <code>GetHolidayResponse</code>.
   * @alias module:model/GetHolidayResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetHolidayResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetHolidayResponse} obj Optional instance to populate.
   * @return {module:model/GetHolidayResponse} The populated <code>GetHolidayResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetHolidayResponse();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [HolidayData]);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
GetHolidayResponse.StatusEnum = {
  /**
   * value: "success"
   * @const
   */
  success: "success",

  /**
   * value: "error"
   * @const
   */
  error: "error"
};
/**
 * @member {module:model/GetHolidayResponse.StatusEnum} status
 */
GetHolidayResponse.prototype.status = undefined;

/**
 * Response data for holiday list
 * @member {Array.<module:model/HolidayData>} data
 */
GetHolidayResponse.prototype.data = undefined;

