/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.79
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MutualFundMetaData} from './MutualFundMetaData';

/**
 * The GetMutualFundOrdersResponse model module.
 * @module model/GetMutualFundOrdersResponse
 * @version v0
 */
export class GetMutualFundOrdersResponse {
  /**
   * Constructs a new <code>GetMutualFundOrdersResponse</code>.
   * @alias module:model/GetMutualFundOrdersResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetMutualFundOrdersResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetMutualFundOrdersResponse} obj Optional instance to populate.
   * @return {module:model/GetMutualFundOrdersResponse} The populated <code>GetMutualFundOrdersResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetMutualFundOrdersResponse();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], Object);
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], Object);
      if (data.hasOwnProperty('meta_data'))
        obj.metaData = MutualFundMetaData.constructFromObject(data['meta_data']);
    }
    return obj;
  }
}

/**
 * @member {Object} status
 */
GetMutualFundOrdersResponse.prototype.status = undefined;

/**
 * Mutual fund orders in the requested window.
 * @member {Object} data
 */
GetMutualFundOrdersResponse.prototype.data = undefined;

/**
 * Meta data for mutual fund orders
 * @member {module:model/MutualFundMetaData} metaData
 */
GetMutualFundOrdersResponse.prototype.metaData = undefined;

