/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MarketQuoteSymbolLtpV3} from './MarketQuoteSymbolLtpV3';

/**
 * The GetMarketQuoteLastTradedPriceResponseV3 model module.
 * @module model/GetMarketQuoteLastTradedPriceResponseV3
 * @version v0
 */
export class GetMarketQuoteLastTradedPriceResponseV3 {
  /**
   * Constructs a new <code>GetMarketQuoteLastTradedPriceResponseV3</code>.
   * @alias module:model/GetMarketQuoteLastTradedPriceResponseV3
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetMarketQuoteLastTradedPriceResponseV3</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetMarketQuoteLastTradedPriceResponseV3} obj Optional instance to populate.
   * @return {module:model/GetMarketQuoteLastTradedPriceResponseV3} The populated <code>GetMarketQuoteLastTradedPriceResponseV3</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetMarketQuoteLastTradedPriceResponseV3();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], {'String': MarketQuoteSymbolLtpV3});
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
GetMarketQuoteLastTradedPriceResponseV3.StatusEnum = {
  /**
   * value: "success"
   * @const
   */
  success: "success",

  /**
   * value: "error"
   * @const
   */
  error: "error",

  /**
   * value: "partial_success"
   * @const
   */
  partialSuccess: "partial_success"
};
/**
 * @member {module:model/GetMarketQuoteLastTradedPriceResponseV3.StatusEnum} status
 */
GetMarketQuoteLastTradedPriceResponseV3.prototype.status = undefined;

/**
 * @member {Object.<String, module:model/MarketQuoteSymbolLtpV3>} data
 */
GetMarketQuoteLastTradedPriceResponseV3.prototype.data = undefined;

