/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import NewsResponseMetaData from './NewsResponseMetaData';

/**
 * The GetNewsResponse model module.
 * @module model/GetNewsResponse
 * @version v0
 */
export default class GetNewsResponse {
  /**
   * Constructs a new <code>GetNewsResponse</code>.
   * @alias module:model/GetNewsResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetNewsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetNewsResponse} obj Optional instance to populate.
   * @return {module:model/GetNewsResponse} The populated <code>GetNewsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetNewsResponse();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], Object);
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], Object);
      if (data.hasOwnProperty('metadata'))
        obj.metadata = NewsResponseMetaData.constructFromObject(data['metadata']);
    }
    return obj;
  }
}

/**
 * @member {Object} status
 */
GetNewsResponse.prototype.status = undefined;

/**
 * @member {Object} data
 */
GetNewsResponse.prototype.data = undefined;

/**
 * @member {module:model/NewsResponseMetaData} metadata
 */
GetNewsResponse.prototype.metadata = undefined;

