/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IncomeStatementData model module.
 * @module model/IncomeStatementData
 * @version v0
 */
export class IncomeStatementData {
  /**
   * Constructs a new <code>IncomeStatementData</code>.
   * @alias module:model/IncomeStatementData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IncomeStatementData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IncomeStatementData} obj Optional instance to populate.
   * @return {module:model/IncomeStatementData} The populated <code>IncomeStatementData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IncomeStatementData();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], Object);
      if (data.hasOwnProperty('time_period'))
        obj.timePeriod = ApiClient.convertToType(data['time_period'], Object);
      if (data.hasOwnProperty('units_in'))
        obj.unitsIn = ApiClient.convertToType(data['units_in'], Object);
      if (data.hasOwnProperty('income_statement'))
        obj.incomeStatement = ApiClient.convertToType(data['income_statement'], Object);
      if (data.hasOwnProperty('full_statement'))
        obj.fullStatement = ApiClient.convertToType(data['full_statement'], Object);
    }
    return obj;
  }
}

/**
 * Report type: consolidated or standalone
 * @member {Object} type
 */
IncomeStatementData.prototype.type = undefined;

/**
 * Time period: yearly or quarterly
 * @member {Object} timePeriod
 */
IncomeStatementData.prototype.timePeriod = undefined;

/**
 * Unit of monetary values
 * @member {Object} unitsIn
 */
IncomeStatementData.prototype.unitsIn = undefined;

/**
 * Income statement entries grouped by type (Revenue, Operating profit, Net profit)
 * @member {Object} incomeStatement
 */
IncomeStatementData.prototype.incomeStatement = undefined;

/**
 * List of financial statement income statement items with historical values
 * @member {Object} fullStatement
 */
IncomeStatementData.prototype.fullStatement = undefined;

