/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IpoApplyData model module.
 * @module model/IpoApplyData
 * @version v0
 */
export class IpoApplyData {
  /**
   * Constructs a new <code>IpoApplyData</code>.
   * @alias module:model/IpoApplyData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpoApplyData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IpoApplyData} obj Optional instance to populate.
   * @return {module:model/IpoApplyData} The populated <code>IpoApplyData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpoApplyData();
      if (data.hasOwnProperty('order_id'))
        obj.orderId = ApiClient.convertToType(data['order_id'], Object);
    }
    return obj;
  }
}

/**
 * Application id created for this IPO application. Pass this as order_id to the get-order and cancel-order APIs
 * @member {Object} orderId
 */
IpoApplyData.prototype.orderId = undefined;

