/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IpoCancelData model module.
 * @module model/IpoCancelData
 * @version v0
 */
export class IpoCancelData {
  /**
   * Constructs a new <code>IpoCancelData</code>.
   * @alias module:model/IpoCancelData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpoCancelData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IpoCancelData} obj Optional instance to populate.
   * @return {module:model/IpoCancelData} The populated <code>IpoCancelData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpoCancelData();
      if (data.hasOwnProperty('order_id'))
        obj.orderId = ApiClient.convertToType(data['order_id'], Object);
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], Object);
    }
    return obj;
  }
}

/**
 * Application id that was cancelled
 * @member {Object} orderId
 */
IpoCancelData.prototype.orderId = undefined;

/**
 * Free-text message returned by the IPO service for the cancellation request
 * @member {Object} status
 */
IpoCancelData.prototype.status = undefined;

