/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IpoInvestorType model module.
 * @module model/IpoInvestorType
 * @version v0
 */
export class IpoInvestorType {
  /**
   * Constructs a new <code>IpoInvestorType</code>.
   * @alias module:model/IpoInvestorType
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpoInvestorType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IpoInvestorType} obj Optional instance to populate.
   * @return {module:model/IpoInvestorType} The populated <code>IpoInvestorType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpoInvestorType();
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], Object);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], Object);
    }
    return obj;
  }
}

/**
 * Investor category the issue accepts. Pass this value as category when applying
 * @member {Object} category
 */
IpoInvestorType.prototype.category = undefined;

/**
 * Human-readable name of the category; null when the IPO service does not provide one
 * @member {Object} description
 */
IpoInvestorType.prototype.description = undefined;

