/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.79
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Pagination} from './Pagination';

/**
 * The IpoMetaData model module.
 * @module model/IpoMetaData
 * @version v0
 */
export class IpoMetaData {
  /**
   * Constructs a new <code>IpoMetaData</code>.
   * @alias module:model/IpoMetaData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpoMetaData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IpoMetaData} obj Optional instance to populate.
   * @return {module:model/IpoMetaData} The populated <code>IpoMetaData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpoMetaData();
      if (data.hasOwnProperty('page'))
        obj.page = Pagination.constructFromObject(data['page']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Pagination} page
 */
IpoMetaData.prototype.page = undefined;

