/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IpoOrderData model module.
 * @module model/IpoOrderData
 * @version v0
 */
export class IpoOrderData {
  /**
   * Constructs a new <code>IpoOrderData</code>.
   * @alias module:model/IpoOrderData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpoOrderData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IpoOrderData} obj Optional instance to populate.
   * @return {module:model/IpoOrderData} The populated <code>IpoOrderData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpoOrderData();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], Object);
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], Object);
      if (data.hasOwnProperty('exchange'))
        obj.exchange = ApiClient.convertToType(data['exchange'], Object);
      if (data.hasOwnProperty('request_id'))
        obj.requestId = ApiClient.convertToType(data['request_id'], Object);
      if (data.hasOwnProperty('order_id'))
        obj.orderId = ApiClient.convertToType(data['order_id'], Object);
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], Object);
      if (data.hasOwnProperty('order_status'))
        obj.orderStatus = ApiClient.convertToType(data['order_status'], Object);
      if (data.hasOwnProperty('payment_status'))
        obj.paymentStatus = ApiClient.convertToType(data['payment_status'], Object);
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], Object);
      if (data.hasOwnProperty('issue_type'))
        obj.issueType = ApiClient.convertToType(data['issue_type'], Object);
      if (data.hasOwnProperty('reason'))
        obj.reason = ApiClient.convertToType(data['reason'], Object);
      if (data.hasOwnProperty('upi'))
        obj.upi = ApiClient.convertToType(data['upi'], Object);
      if (data.hasOwnProperty('upi_amount_blocked'))
        obj.upiAmountBlocked = ApiClient.convertToType(data['upi_amount_blocked'], Object);
      if (data.hasOwnProperty('nse_submitted_date'))
        obj.nseSubmittedDate = ApiClient.convertToType(data['nse_submitted_date'], Object);
      if (data.hasOwnProperty('bse_submitted_date'))
        obj.bseSubmittedDate = ApiClient.convertToType(data['bse_submitted_date'], Object);
      if (data.hasOwnProperty('mandate_approved_date'))
        obj.mandateApprovedDate = ApiClient.convertToType(data['mandate_approved_date'], Object);
      if (data.hasOwnProperty('rejection_date'))
        obj.rejectionDate = ApiClient.convertToType(data['rejection_date'], Object);
      if (data.hasOwnProperty('mandate_rejection_date'))
        obj.mandateRejectionDate = ApiClient.convertToType(data['mandate_rejection_date'], Object);
      if (data.hasOwnProperty('cancel_requested_date'))
        obj.cancelRequestedDate = ApiClient.convertToType(data['cancel_requested_date'], Object);
      if (data.hasOwnProperty('cancel_accepted_date'))
        obj.cancelAcceptedDate = ApiClient.convertToType(data['cancel_accepted_date'], Object);
      if (data.hasOwnProperty('units_allotted'))
        obj.unitsAllotted = ApiClient.convertToType(data['units_allotted'], Object);
      if (data.hasOwnProperty('bids'))
        obj.bids = ApiClient.convertToType(data['bids'], Object);
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], Object);
      if (data.hasOwnProperty('last_updated_at'))
        obj.lastUpdatedAt = ApiClient.convertToType(data['last_updated_at'], Object);
    }
    return obj;
  }
}

/**
 * Reference id of the IPO the application was placed against
 * @member {Object} id
 */
IpoOrderData.prototype.id = undefined;

/**
 * Trading symbol of the issuer
 * @member {Object} symbol
 */
IpoOrderData.prototype.symbol = undefined;

/**
 * Exchange the application was submitted to. Casing follows the exchange feed and may vary
 * @member {Object} exchange
 */
IpoOrderData.prototype.exchange = undefined;

/**
 * Id of the request that created the application
 * @member {Object} requestId
 */
IpoOrderData.prototype.requestId = undefined;

/**
 * Application id. Pass this as order_id to the get-order and cancel-order APIs
 * @member {Object} orderId
 */
IpoOrderData.prototype.orderId = undefined;

/**
 * Lifecycle stage of the application. Known values: awaiting_mandate, ipo_allotted, ipo_not_allotted, application_deleted
 * @member {Object} status
 */
IpoOrderData.prototype.status = undefined;

/**
 * Outcome of the application. Known values: success, allotted, not_allotted
 * @member {Object} orderStatus
 */
IpoOrderData.prototype.orderStatus = undefined;

/**
 * State of the UPI mandate backing the application. Known values: pending, mandate_accepted
 * @member {Object} paymentStatus
 */
IpoOrderData.prototype.paymentStatus = undefined;

/**
 * Investor category the application was placed under. IND (individual) and HNI can be applied for; EMP appears on employee-quota applications
 * @member {Object} category
 */
IpoOrderData.prototype.category = undefined;

/**
 * Issue type of the IPO. `regular` is a mainboard issue
 * @member {Object} issueType
 */
IpoOrderData.prototype.issueType = undefined;

/**
 * Free-text reason from the exchange or registrar explaining the current status
 * @member {Object} reason
 */
IpoOrderData.prototype.reason = undefined;

/**
 * UPI id the mandate was raised against
 * @member {Object} upi
 */
IpoOrderData.prototype.upi = undefined;

/**
 * Amount blocked in the applicant's bank account for this application, as a decimal string. Absent until the mandate is accepted
 * @member {Object} upiAmountBlocked
 */
IpoOrderData.prototype.upiAmountBlocked = undefined;

/**
 * When the application was submitted to NSE, in yyyy-MM-dd'T'HH:mm:ss; null if not submitted there
 * @member {Object} nseSubmittedDate
 */
IpoOrderData.prototype.nseSubmittedDate = undefined;

/**
 * When the application was submitted to BSE, in yyyy-MM-dd'T'HH:mm:ss; null if not submitted there
 * @member {Object} bseSubmittedDate
 */
IpoOrderData.prototype.bseSubmittedDate = undefined;

/**
 * When the UPI mandate was approved; null until approved
 * @member {Object} mandateApprovedDate
 */
IpoOrderData.prototype.mandateApprovedDate = undefined;

/**
 * When the application was rejected; null unless rejected
 * @member {Object} rejectionDate
 */
IpoOrderData.prototype.rejectionDate = undefined;

/**
 * When the UPI mandate was rejected; null unless rejected
 * @member {Object} mandateRejectionDate
 */
IpoOrderData.prototype.mandateRejectionDate = undefined;

/**
 * When cancellation was requested; null unless a cancellation was raised
 * @member {Object} cancelRequestedDate
 */
IpoOrderData.prototype.cancelRequestedDate = undefined;

/**
 * When cancellation was accepted; null unless the cancellation completed
 * @member {Object} cancelAcceptedDate
 */
IpoOrderData.prototype.cancelAcceptedDate = undefined;

/**
 * Shares allotted. 0 until allotment completes, and on applications that were not allotted
 * @member {Object} unitsAllotted
 */
IpoOrderData.prototype.unitsAllotted = undefined;

/**
 * Bids placed in this application
 * @member {Object} bids
 */
IpoOrderData.prototype.bids = undefined;

/**
 * When the application was created, in yyyy-MM-dd'T'HH:mm:ss
 * @member {Object} createdAt
 */
IpoOrderData.prototype.createdAt = undefined;

/**
 * When the application was last updated, in yyyy-MM-dd'T'HH:mm:ss
 * @member {Object} lastUpdatedAt
 */
IpoOrderData.prototype.lastUpdatedAt = undefined;

