/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IpoOrderBid model module.
 * @module model/IpoOrderBid
 * @version v0
 */
export class IpoOrderBid {
  /**
   * Constructs a new <code>IpoOrderBid</code>.
   * @alias module:model/IpoOrderBid
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpoOrderBid</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IpoOrderBid} obj Optional instance to populate.
   * @return {module:model/IpoOrderBid} The populated <code>IpoOrderBid</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpoOrderBid();
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], Object);
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], Object);
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], Object);
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], Object);
    }
    return obj;
  }
}

/**
 * Number of shares bid for
 * @member {Object} quantity
 */
IpoOrderBid.prototype.quantity = undefined;

/**
 * Bid price per share
 * @member {Object} price
 */
IpoOrderBid.prototype.price = undefined;

/**
 * Value of the bid, quantity x price
 * @member {Object} amount
 */
IpoOrderBid.prototype.amount = undefined;

/**
 * Message from the exchange for this bid, when one was returned
 * @member {Object} message
 */
IpoOrderBid.prototype.message = undefined;

