/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.79
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IpoRegistrarInfo model module.
 * @module model/IpoRegistrarInfo
 * @version v0
 */
export class IpoRegistrarInfo {
  /**
   * Constructs a new <code>IpoRegistrarInfo</code>.
   * @alias module:model/IpoRegistrarInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpoRegistrarInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IpoRegistrarInfo} obj Optional instance to populate.
   * @return {module:model/IpoRegistrarInfo} The populated <code>IpoRegistrarInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpoRegistrarInfo();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], Object);
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], Object);
      if (data.hasOwnProperty('contact_name'))
        obj.contactName = ApiClient.convertToType(data['contact_name'], Object);
      if (data.hasOwnProperty('contact_number'))
        obj.contactNumber = ApiClient.convertToType(data['contact_number'], Object);
      if (data.hasOwnProperty('website'))
        obj.website = ApiClient.convertToType(data['website'], Object);
      if (data.hasOwnProperty('registrar'))
        obj.registrar = ApiClient.convertToType(data['registrar'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} name
 */
IpoRegistrarInfo.prototype.name = undefined;

/**
 * @member {Object} email
 */
IpoRegistrarInfo.prototype.email = undefined;

/**
 * @member {Object} contactName
 */
IpoRegistrarInfo.prototype.contactName = undefined;

/**
 * @member {Object} contactNumber
 */
IpoRegistrarInfo.prototype.contactNumber = undefined;

/**
 * @member {Object} website
 */
IpoRegistrarInfo.prototype.website = undefined;

/**
 * @member {Object} registrar
 */
IpoRegistrarInfo.prototype.registrar = undefined;

