/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.79
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IpoTimeline model module.
 * @module model/IpoTimeline
 * @version v0
 */
export class IpoTimeline {
  /**
   * Constructs a new <code>IpoTimeline</code>.
   * @alias module:model/IpoTimeline
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpoTimeline</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IpoTimeline} obj Optional instance to populate.
   * @return {module:model/IpoTimeline} The populated <code>IpoTimeline</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpoTimeline();
      if (data.hasOwnProperty('pre_apply_start_date'))
        obj.preApplyStartDate = ApiClient.convertToType(data['pre_apply_start_date'], Object);
      if (data.hasOwnProperty('application_start_date'))
        obj.applicationStartDate = ApiClient.convertToType(data['application_start_date'], Object);
      if (data.hasOwnProperty('application_end_date'))
        obj.applicationEndDate = ApiClient.convertToType(data['application_end_date'], Object);
      if (data.hasOwnProperty('allotment_start_date'))
        obj.allotmentStartDate = ApiClient.convertToType(data['allotment_start_date'], Object);
      if (data.hasOwnProperty('allotment_date'))
        obj.allotmentDate = ApiClient.convertToType(data['allotment_date'], Object);
      if (data.hasOwnProperty('refund_initiation_date'))
        obj.refundInitiationDate = ApiClient.convertToType(data['refund_initiation_date'], Object);
      if (data.hasOwnProperty('listing_date'))
        obj.listingDate = ApiClient.convertToType(data['listing_date'], Object);
      if (data.hasOwnProperty('mandate_end_date'))
        obj.mandateEndDate = ApiClient.convertToType(data['mandate_end_date'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} preApplyStartDate
 */
IpoTimeline.prototype.preApplyStartDate = undefined;

/**
 * @member {Object} applicationStartDate
 */
IpoTimeline.prototype.applicationStartDate = undefined;

/**
 * @member {Object} applicationEndDate
 */
IpoTimeline.prototype.applicationEndDate = undefined;

/**
 * @member {Object} allotmentStartDate
 */
IpoTimeline.prototype.allotmentStartDate = undefined;

/**
 * @member {Object} allotmentDate
 */
IpoTimeline.prototype.allotmentDate = undefined;

/**
 * @member {Object} refundInitiationDate
 */
IpoTimeline.prototype.refundInitiationDate = undefined;

/**
 * @member {Object} listingDate
 */
IpoTimeline.prototype.listingDate = undefined;

/**
 * @member {Object} mandateEndDate
 */
IpoTimeline.prototype.mandateEndDate = undefined;

