/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The KeyRatioData model module.
 * @module model/KeyRatioData
 * @version v0
 */
export class KeyRatioData {
  /**
   * Constructs a new <code>KeyRatioData</code>.
   * @alias module:model/KeyRatioData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>KeyRatioData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KeyRatioData} obj Optional instance to populate.
   * @return {module:model/KeyRatioData} The populated <code>KeyRatioData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new KeyRatioData();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], Object);
      if (data.hasOwnProperty('company_value'))
        obj.companyValue = ApiClient.convertToType(data['company_value'], Object);
      if (data.hasOwnProperty('sector_value'))
        obj.sectorValue = ApiClient.convertToType(data['sector_value'], Object);
    }
    return obj;
  }
}

/**
 * Name of the ratio
 * @member {Object} name
 */
KeyRatioData.prototype.name = undefined;

/**
 * Ratio value for the company
 * @member {Object} companyValue
 */
KeyRatioData.prototype.companyValue = undefined;

/**
 * Ratio value for the sector reference
 * @member {Object} sectorValue
 */
KeyRatioData.prototype.sectorValue = undefined;

