/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The KillSwitchSegmentUpdateRequest model module.
 * @module model/KillSwitchSegmentUpdateRequest
 * @version v0
 */
export class KillSwitchSegmentUpdateRequest {
  /**
   * Constructs a new <code>KillSwitchSegmentUpdateRequest</code>.
   * @alias module:model/KillSwitchSegmentUpdateRequest
   * @class
   * @param segment {Object} 
   * @param action {Object} 
   */
  constructor(segment, action) {
    this.segment = segment;
    this.action = action;
  }

  /**
   * Constructs a <code>KillSwitchSegmentUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KillSwitchSegmentUpdateRequest} obj Optional instance to populate.
   * @return {module:model/KillSwitchSegmentUpdateRequest} The populated <code>KillSwitchSegmentUpdateRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new KillSwitchSegmentUpdateRequest();
      if (data.hasOwnProperty('segment'))
        obj.segment = ApiClient.convertToType(data['segment'], Object);
      if (data.hasOwnProperty('action'))
        obj.action = ApiClient.convertToType(data['action'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} segment
 */
KillSwitchSegmentUpdateRequest.prototype.segment = undefined;

/**
 * @member {Object} action
 */
KillSwitchSegmentUpdateRequest.prototype.action = undefined;

