/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MarginFromPledge model module.
 * @module model/MarginFromPledge
 * @version v0
 */
export class MarginFromPledge {
  /**
   * Constructs a new <code>MarginFromPledge</code>.
   * @alias module:model/MarginFromPledge
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MarginFromPledge</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MarginFromPledge} obj Optional instance to populate.
   * @return {module:model/MarginFromPledge} The populated <code>MarginFromPledge</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MarginFromPledge();
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], Object);
      if (data.hasOwnProperty('equity'))
        obj.equity = ApiClient.convertToType(data['equity'], Object);
      if (data.hasOwnProperty('mutual_funds'))
        obj.mutualFunds = ApiClient.convertToType(data['mutual_funds'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} total
 */
MarginFromPledge.prototype.total = undefined;

/**
 * @member {Object} equity
 */
MarginFromPledge.prototype.equity = undefined;

/**
 * @member {Object} mutualFunds
 */
MarginFromPledge.prototype.mutualFunds = undefined;

