/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.82
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DepthMap} from './DepthMap';
import {OhlcV3} from './OhlcV3';

/**
 * The MarketQuoteSymbolV3 model module.
 * @module model/MarketQuoteSymbolV3
 * @version v0
 */
export class MarketQuoteSymbolV3 {
  /**
   * Constructs a new <code>MarketQuoteSymbolV3</code>.
   * @alias module:model/MarketQuoteSymbolV3
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MarketQuoteSymbolV3</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MarketQuoteSymbolV3} obj Optional instance to populate.
   * @return {module:model/MarketQuoteSymbolV3} The populated <code>MarketQuoteSymbolV3</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MarketQuoteSymbolV3();
      if (data.hasOwnProperty('ohlc'))
        obj.ohlc = OhlcV3.constructFromObject(data['ohlc']);
      if (data.hasOwnProperty('depth'))
        obj.depth = DepthMap.constructFromObject(data['depth']);
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'String');
      if (data.hasOwnProperty('instrument_token'))
        obj.instrumentToken = ApiClient.convertToType(data['instrument_token'], 'String');
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], 'String');
      if (data.hasOwnProperty('last_price'))
        obj.lastPrice = ApiClient.convertToType(data['last_price'], 'Number');
      if (data.hasOwnProperty('volume'))
        obj.volume = ApiClient.convertToType(data['volume'], 'Number');
      if (data.hasOwnProperty('average_price'))
        obj.averagePrice = ApiClient.convertToType(data['average_price'], 'Number');
      if (data.hasOwnProperty('oi'))
        obj.oi = ApiClient.convertToType(data['oi'], 'Number');
      if (data.hasOwnProperty('net_change'))
        obj.netChange = ApiClient.convertToType(data['net_change'], 'Number');
      if (data.hasOwnProperty('total_buy_quantity'))
        obj.totalBuyQuantity = ApiClient.convertToType(data['total_buy_quantity'], 'Number');
      if (data.hasOwnProperty('total_sell_quantity'))
        obj.totalSellQuantity = ApiClient.convertToType(data['total_sell_quantity'], 'Number');
      if (data.hasOwnProperty('lower_circuit_limit'))
        obj.lowerCircuitLimit = ApiClient.convertToType(data['lower_circuit_limit'], 'Number');
      if (data.hasOwnProperty('upper_circuit_limit'))
        obj.upperCircuitLimit = ApiClient.convertToType(data['upper_circuit_limit'], 'Number');
      if (data.hasOwnProperty('last_trade_time'))
        obj.lastTradeTime = ApiClient.convertToType(data['last_trade_time'], 'String');
      if (data.hasOwnProperty('oi_day_high'))
        obj.oiDayHigh = ApiClient.convertToType(data['oi_day_high'], 'Number');
      if (data.hasOwnProperty('oi_day_low'))
        obj.oiDayLow = ApiClient.convertToType(data['oi_day_low'], 'Number');
      if (data.hasOwnProperty('prev_close_price'))
        obj.prevClosePrice = ApiClient.convertToType(data['prev_close_price'], 'Number');
      if (data.hasOwnProperty('year_high'))
        obj.yearHigh = ApiClient.convertToType(data['year_high'], 'Number');
      if (data.hasOwnProperty('year_low'))
        obj.yearLow = ApiClient.convertToType(data['year_low'], 'Number');
      if (data.hasOwnProperty('previous_oi'))
        obj.previousOi = ApiClient.convertToType(data['previous_oi'], 'Number');
      if (data.hasOwnProperty('indicative_equilibrium_price'))
        obj.indicativeEquilibriumPrice = ApiClient.convertToType(data['indicative_equilibrium_price'], 'Number');
      if (data.hasOwnProperty('reference_price'))
        obj.referencePrice = ApiClient.convertToType(data['reference_price'], 'Number');
      if (data.hasOwnProperty('indicative_equilibrium_quantity'))
        obj.indicativeEquilibriumQuantity = ApiClient.convertToType(data['indicative_equilibrium_quantity'], 'Number');
      if (data.hasOwnProperty('indicative_imbalance_quantity_total'))
        obj.indicativeImbalanceQuantityTotal = ApiClient.convertToType(data['indicative_imbalance_quantity_total'], 'Number');
      if (data.hasOwnProperty('indicative_imbalance_quantity_market'))
        obj.indicativeImbalanceQuantityMarket = ApiClient.convertToType(data['indicative_imbalance_quantity_market'], 'Number');
      if (data.hasOwnProperty('cas_eligible'))
        obj.casEligible = ApiClient.convertToType(data['cas_eligible'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:model/OhlcV3} ohlc
 */
MarketQuoteSymbolV3.prototype.ohlc = undefined;

/**
 * @member {module:model/DepthMap} depth
 */
MarketQuoteSymbolV3.prototype.depth = undefined;

/**
 * Time in milliseconds at which the feeds was updated
 * @member {String} timestamp
 */
MarketQuoteSymbolV3.prototype.timestamp = undefined;

/**
 * Key issued by Upstox for the instrument
 * @member {String} instrumentToken
 */
MarketQuoteSymbolV3.prototype.instrumentToken = undefined;

/**
 * Shows the trading symbol of the instrument
 * @member {String} symbol
 */
MarketQuoteSymbolV3.prototype.symbol = undefined;

/**
 * The last traded price of symbol
 * @member {Number} lastPrice
 */
MarketQuoteSymbolV3.prototype.lastPrice = undefined;

/**
 * The volume traded today on symbol
 * @member {Number} volume
 */
MarketQuoteSymbolV3.prototype.volume = undefined;

/**
 * Average price
 * @member {Number} averagePrice
 */
MarketQuoteSymbolV3.prototype.averagePrice = undefined;

/**
 * Total number of outstanding contracts held by market participants exchange-wide (only F&O)
 * @member {Number} oi
 */
MarketQuoteSymbolV3.prototype.oi = undefined;

/**
 * The absolute change from yesterday's close to last traded price
 * @member {Number} netChange
 */
MarketQuoteSymbolV3.prototype.netChange = undefined;

/**
 * The total number of bid quantity available for trading
 * @member {Number} totalBuyQuantity
 */
MarketQuoteSymbolV3.prototype.totalBuyQuantity = undefined;

/**
 * The total number of ask quantity available for trading
 * @member {Number} totalSellQuantity
 */
MarketQuoteSymbolV3.prototype.totalSellQuantity = undefined;

/**
 * The lower circuit of symbol
 * @member {Number} lowerCircuitLimit
 */
MarketQuoteSymbolV3.prototype.lowerCircuitLimit = undefined;

/**
 * The upper circuit of symbol
 * @member {Number} upperCircuitLimit
 */
MarketQuoteSymbolV3.prototype.upperCircuitLimit = undefined;

/**
 * Time in milliseconds at which last trade happened
 * @member {String} lastTradeTime
 */
MarketQuoteSymbolV3.prototype.lastTradeTime = undefined;

/**
 * The highest open interest recorded on symbol during the day
 * @member {Number} oiDayHigh
 */
MarketQuoteSymbolV3.prototype.oiDayHigh = undefined;

/**
 * The lowest open interest recorded on symbol during the day
 * @member {Number} oiDayLow
 */
MarketQuoteSymbolV3.prototype.oiDayLow = undefined;

/**
 * The close price of the symbol from the previous session of trading
 * @member {Number} prevClosePrice
 */
MarketQuoteSymbolV3.prototype.prevClosePrice = undefined;

/**
 * The highest price of the symbol over the trailing year
 * @member {Number} yearHigh
 */
MarketQuoteSymbolV3.prototype.yearHigh = undefined;

/**
 * The lowest price of the symbol over the trailing year
 * @member {Number} yearLow
 */
MarketQuoteSymbolV3.prototype.yearLow = undefined;

/**
 * The open interest of the symbol from the previous session (only F&O)
 * @member {Number} previousOi
 */
MarketQuoteSymbolV3.prototype.previousOi = undefined;

/**
 * The indicative equilibrium price discovered during the call auction session
 * @member {Number} indicativeEquilibriumPrice
 */
MarketQuoteSymbolV3.prototype.indicativeEquilibriumPrice = undefined;

/**
 * The reference price against which the call auction price band is applied
 * @member {Number} referencePrice
 */
MarketQuoteSymbolV3.prototype.referencePrice = undefined;

/**
 * The indicative equilibrium quantity matched at the indicative equilibrium price
 * @member {Number} indicativeEquilibriumQuantity
 */
MarketQuoteSymbolV3.prototype.indicativeEquilibriumQuantity = undefined;

/**
 * The total indicative imbalance quantity in the call auction order book
 * @member {Number} indicativeImbalanceQuantityTotal
 */
MarketQuoteSymbolV3.prototype.indicativeImbalanceQuantityTotal = undefined;

/**
 * The market-order component of the indicative imbalance quantity in the call auction order book
 * @member {Number} indicativeImbalanceQuantityMarket
 */
MarketQuoteSymbolV3.prototype.indicativeImbalanceQuantityMarket = undefined;

/**
 * Whether the symbol is eligible for the call auction session
 * @member {Boolean} casEligible
 */
MarketQuoteSymbolV3.prototype.casEligible = undefined;
