/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OhlcV3} from './OhlcV3';

/**
 * The MarketQuoteOHLCV3 model module.
 * @module model/MarketQuoteOHLCV3
 * @version v0
 */
export class MarketQuoteOHLCV3 {
  /**
   * Constructs a new <code>MarketQuoteOHLCV3</code>.
   * @alias module:model/MarketQuoteOHLCV3
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MarketQuoteOHLCV3</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MarketQuoteOHLCV3} obj Optional instance to populate.
   * @return {module:model/MarketQuoteOHLCV3} The populated <code>MarketQuoteOHLCV3</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MarketQuoteOHLCV3();
      if (data.hasOwnProperty('last_price'))
        obj.lastPrice = ApiClient.convertToType(data['last_price'], 'Number');
      if (data.hasOwnProperty('instrument_token'))
        obj.instrumentToken = ApiClient.convertToType(data['instrument_token'], 'String');
      if (data.hasOwnProperty('prev_ohlc'))
        obj.prevOhlc = OhlcV3.constructFromObject(data['prev_ohlc']);
      if (data.hasOwnProperty('live_ohlc'))
        obj.liveOhlc = OhlcV3.constructFromObject(data['live_ohlc']);
    }
    return obj;
  }
}

/**
 * The last traded price of symbol
 * @member {Number} lastPrice
 */
MarketQuoteOHLCV3.prototype.lastPrice = undefined;

/**
 * @member {String} instrumentToken
 */
MarketQuoteOHLCV3.prototype.instrumentToken = undefined;

/**
 * @member {module:model/OhlcV3} prevOhlc
 */
MarketQuoteOHLCV3.prototype.prevOhlc = undefined;

/**
 * @member {module:model/OhlcV3} liveOhlc
 */
MarketQuoteOHLCV3.prototype.liveOhlc = undefined;

