/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MarketQuoteOptionGreekV3 model module.
 * @module model/MarketQuoteOptionGreekV3
 * @version v0
 */
export class MarketQuoteOptionGreekV3 {
  /**
   * Constructs a new <code>MarketQuoteOptionGreekV3</code>.
   * @alias module:model/MarketQuoteOptionGreekV3
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MarketQuoteOptionGreekV3</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MarketQuoteOptionGreekV3} obj Optional instance to populate.
   * @return {module:model/MarketQuoteOptionGreekV3} The populated <code>MarketQuoteOptionGreekV3</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MarketQuoteOptionGreekV3();
      if (data.hasOwnProperty('last_price'))
        obj.lastPrice = ApiClient.convertToType(data['last_price'], 'Number');
      if (data.hasOwnProperty('instrument_token'))
        obj.instrumentToken = ApiClient.convertToType(data['instrument_token'], 'String');
      if (data.hasOwnProperty('ltq'))
        obj.ltq = ApiClient.convertToType(data['ltq'], 'Number');
      if (data.hasOwnProperty('volume'))
        obj.volume = ApiClient.convertToType(data['volume'], 'Number');
      if (data.hasOwnProperty('cp'))
        obj.cp = ApiClient.convertToType(data['cp'], 'Number');
      if (data.hasOwnProperty('iv'))
        obj.iv = ApiClient.convertToType(data['iv'], 'Number');
      if (data.hasOwnProperty('vega'))
        obj.vega = ApiClient.convertToType(data['vega'], 'Number');
      if (data.hasOwnProperty('gamma'))
        obj.gamma = ApiClient.convertToType(data['gamma'], 'Number');
      if (data.hasOwnProperty('theta'))
        obj.theta = ApiClient.convertToType(data['theta'], 'Number');
      if (data.hasOwnProperty('delta'))
        obj.delta = ApiClient.convertToType(data['delta'], 'Number');
      if (data.hasOwnProperty('oi'))
        obj.oi = ApiClient.convertToType(data['oi'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} lastPrice
 */
MarketQuoteOptionGreekV3.prototype.lastPrice = undefined;

/**
 * @member {String} instrumentToken
 */
MarketQuoteOptionGreekV3.prototype.instrumentToken = undefined;

/**
 * @member {Number} ltq
 */
MarketQuoteOptionGreekV3.prototype.ltq = undefined;

/**
 * @member {Number} volume
 */
MarketQuoteOptionGreekV3.prototype.volume = undefined;

/**
 * @member {Number} cp
 */
MarketQuoteOptionGreekV3.prototype.cp = undefined;

/**
 * @member {Number} iv
 */
MarketQuoteOptionGreekV3.prototype.iv = undefined;

/**
 * @member {Number} vega
 */
MarketQuoteOptionGreekV3.prototype.vega = undefined;

/**
 * @member {Number} gamma
 */
MarketQuoteOptionGreekV3.prototype.gamma = undefined;

/**
 * @member {Number} theta
 */
MarketQuoteOptionGreekV3.prototype.theta = undefined;

/**
 * @member {Number} delta
 */
MarketQuoteOptionGreekV3.prototype.delta = undefined;

/**
 * @member {Number} oi
 */
MarketQuoteOptionGreekV3.prototype.oi = undefined;

