/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MarketStatusData model module.
 * @module model/MarketStatusData
 * @version v0
 */
export class MarketStatusData {
  /**
   * Constructs a new <code>MarketStatusData</code>.
   * Response data for market live status
   * @alias module:model/MarketStatusData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MarketStatusData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MarketStatusData} obj Optional instance to populate.
   * @return {module:model/MarketStatusData} The populated <code>MarketStatusData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MarketStatusData();
      if (data.hasOwnProperty('exchange'))
        obj.exchange = ApiClient.convertToType(data['exchange'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('last_updated'))
        obj.lastUpdated = ApiClient.convertToType(data['last_updated'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} exchange
 */
MarketStatusData.prototype.exchange = undefined;

/**
 * @member {String} status
 */
MarketStatusData.prototype.status = undefined;

/**
 * @member {Number} lastUpdated
 */
MarketStatusData.prototype.lastUpdated = undefined;

