/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.79
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ModifyPayoutRequest model module.
 * @module model/ModifyPayoutRequest
 * @version v0
 */
export class ModifyPayoutRequest {
  /**
   * Constructs a new <code>ModifyPayoutRequest</code>.
   * @alias module:model/ModifyPayoutRequest
   * @class
   * @param amount {Object} Withdrawal amount in INR
   */
  constructor(amount) {
    this.amount = amount;
  }

  /**
   * Constructs a <code>ModifyPayoutRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModifyPayoutRequest} obj Optional instance to populate.
   * @return {module:model/ModifyPayoutRequest} The populated <code>ModifyPayoutRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModifyPayoutRequest();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], Object);
    }
    return obj;
  }
}

/**
 * Withdrawal amount in INR
 * @member {Object} amount
 */
ModifyPayoutRequest.prototype.amount = undefined;

