/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MultiOrderV3Data model module.
 * @module model/MultiOrderV3Data
 * @version v0
 */
export class MultiOrderV3Data {
  /**
   * Constructs a new <code>MultiOrderV3Data</code>.
   * @alias module:model/MultiOrderV3Data
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MultiOrderV3Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MultiOrderV3Data} obj Optional instance to populate.
   * @return {module:model/MultiOrderV3Data} The populated <code>MultiOrderV3Data</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MultiOrderV3Data();
      if (data.hasOwnProperty('order_ids'))
        obj.orderIds = ApiClient.convertToType(data['order_ids'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} orderIds
 */
MultiOrderV3Data.prototype.orderIds = undefined;

