/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.79
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MutualFundOrderData model module.
 * @module model/MutualFundOrderData
 * @version v0
 */
export class MutualFundOrderData {
  /**
   * Constructs a new <code>MutualFundOrderData</code>.
   * @alias module:model/MutualFundOrderData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MutualFundOrderData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MutualFundOrderData} obj Optional instance to populate.
   * @return {module:model/MutualFundOrderData} The populated <code>MutualFundOrderData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MutualFundOrderData();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], Object);
      if (data.hasOwnProperty('folio'))
        obj.folio = ApiClient.convertToType(data['folio'], Object);
      if (data.hasOwnProperty('fund'))
        obj.fund = ApiClient.convertToType(data['fund'], Object);
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], Object);
      if (data.hasOwnProperty('variety'))
        obj.variety = ApiClient.convertToType(data['variety'], Object);
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], Object);
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], Object);
      if (data.hasOwnProperty('order_id'))
        obj.orderId = ApiClient.convertToType(data['order_id'], Object);
      if (data.hasOwnProperty('exchange_order_id'))
        obj.exchangeOrderId = ApiClient.convertToType(data['exchange_order_id'], Object);
      if (data.hasOwnProperty('instrument_key'))
        obj.instrumentKey = ApiClient.convertToType(data['instrument_key'], Object);
      if (data.hasOwnProperty('status_message'))
        obj.statusMessage = ApiClient.convertToType(data['status_message'], Object);
      if (data.hasOwnProperty('order_timestamp'))
        obj.orderTimestamp = ApiClient.convertToType(data['order_timestamp'], Object);
      if (data.hasOwnProperty('exchange_timestamp'))
        obj.exchangeTimestamp = ApiClient.convertToType(data['exchange_timestamp'], Object);
      if (data.hasOwnProperty('settlement_id'))
        obj.settlementId = ApiClient.convertToType(data['settlement_id'], Object);
      if (data.hasOwnProperty('transaction_type'))
        obj.transactionType = ApiClient.convertToType(data['transaction_type'], Object);
      if (data.hasOwnProperty('purchase_type'))
        obj.purchaseType = ApiClient.convertToType(data['purchase_type'], Object);
      if (data.hasOwnProperty('last_price'))
        obj.lastPrice = ApiClient.convertToType(data['last_price'], Object);
      if (data.hasOwnProperty('average_price'))
        obj.averagePrice = ApiClient.convertToType(data['average_price'], Object);
      if (data.hasOwnProperty('last_price_date'))
        obj.lastPriceDate = ApiClient.convertToType(data['last_price_date'], Object);
    }
    return obj;
  }
}

/**
 * Current status of the order.
 * @member {Object} status
 */
MutualFundOrderData.prototype.status = undefined;

/**
 * Folio number, when allotted.
 * @member {Object} folio
 */
MutualFundOrderData.prototype.folio = undefined;

/**
 * Display name of the fund.
 * @member {Object} fund
 */
MutualFundOrderData.prototype.fund = undefined;

/**
 * Order amount.
 * @member {Object} amount
 */
MutualFundOrderData.prototype.amount = undefined;

/**
 * Order variety or channel-specific classification, if available.
 * @member {Object} variety
 */
MutualFundOrderData.prototype.variety = undefined;

/**
 * Units allotted or sold.
 * @member {Object} quantity
 */
MutualFundOrderData.prototype.quantity = undefined;

/**
 * Price or NAV used for the transaction, when available.
 * @member {Object} price
 */
MutualFundOrderData.prototype.price = undefined;

/**
 * Unique order identifier.
 * @member {Object} orderId
 */
MutualFundOrderData.prototype.orderId = undefined;

/**
 * Exchange-generated order id, if available.
 * @member {Object} exchangeOrderId
 */
MutualFundOrderData.prototype.exchangeOrderId = undefined;

/**
 * ISIN of the fund, when available.
 * @member {Object} instrumentKey
 */
MutualFundOrderData.prototype.instrumentKey = undefined;

/**
 * Human-readable status or rejection reason.
 * @member {Object} statusMessage
 */
MutualFundOrderData.prototype.statusMessage = undefined;

/**
 * Timestamp when the order was registered.
 * @member {Object} orderTimestamp
 */
MutualFundOrderData.prototype.orderTimestamp = undefined;

/**
 * Exchange date for the order, if available.
 * @member {Object} exchangeTimestamp
 */
MutualFundOrderData.prototype.exchangeTimestamp = undefined;

/**
 * Exchange settlement id, if available.
 * @member {Object} settlementId
 */
MutualFundOrderData.prototype.settlementId = undefined;

/**
 * BUY or SELL.
 * @member {Object} transactionType
 */
MutualFundOrderData.prototype.transactionType = undefined;

/**
 * FRESH or ADDITIONAL for buys, when available.
 * @member {Object} purchaseType
 */
MutualFundOrderData.prototype.purchaseType = undefined;

/**
 * Last known NAV.
 * @member {Object} lastPrice
 */
MutualFundOrderData.prototype.lastPrice = undefined;

/**
 * Allotted or sold NAV.
 * @member {Object} averagePrice
 */
MutualFundOrderData.prototype.averagePrice = undefined;

/**
 * Date for which last NAV is available.
 * @member {Object} lastPriceDate
 */
MutualFundOrderData.prototype.lastPriceDate = undefined;

