/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.79
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MutualFundHoldingData model module.
 * @module model/MutualFundHoldingData
 * @version v0
 */
export class MutualFundHoldingData {
  /**
   * Constructs a new <code>MutualFundHoldingData</code>.
   * @alias module:model/MutualFundHoldingData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MutualFundHoldingData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MutualFundHoldingData} obj Optional instance to populate.
   * @return {module:model/MutualFundHoldingData} The populated <code>MutualFundHoldingData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MutualFundHoldingData();
      if (data.hasOwnProperty('folio'))
        obj.folio = ApiClient.convertToType(data['folio'], Object);
      if (data.hasOwnProperty('fund'))
        obj.fund = ApiClient.convertToType(data['fund'], Object);
      if (data.hasOwnProperty('pnl'))
        obj.pnl = ApiClient.convertToType(data['pnl'], Object);
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], Object);
      if (data.hasOwnProperty('instrument_key'))
        obj.instrumentKey = ApiClient.convertToType(data['instrument_key'], Object);
      if (data.hasOwnProperty('average_price'))
        obj.averagePrice = ApiClient.convertToType(data['average_price'], Object);
      if (data.hasOwnProperty('last_price'))
        obj.lastPrice = ApiClient.convertToType(data['last_price'], Object);
      if (data.hasOwnProperty('last_price_date'))
        obj.lastPriceDate = ApiClient.convertToType(data['last_price_date'], Object);
      if (data.hasOwnProperty('pledged_quantity'))
        obj.pledgedQuantity = ApiClient.convertToType(data['pledged_quantity'], Object);
    }
    return obj;
  }
}

/**
 * Folio number when available.
 * @member {Object} folio
 */
MutualFundHoldingData.prototype.folio = undefined;

/**
 * Fund display name when available.
 * @member {Object} fund
 */
MutualFundHoldingData.prototype.fund = undefined;

/**
 * Unrealized P/L.
 * @member {Object} pnl
 */
MutualFundHoldingData.prototype.pnl = undefined;

/**
 * Units held.
 * @member {Object} quantity
 */
MutualFundHoldingData.prototype.quantity = undefined;

/**
 * ISIN of the fund, when available.
 * @member {Object} instrumentKey
 */
MutualFundHoldingData.prototype.instrumentKey = undefined;

/**
 * Average cost per unit.
 * @member {Object} averagePrice
 */
MutualFundHoldingData.prototype.averagePrice = undefined;

/**
 * Last available NAV.
 * @member {Object} lastPrice
 */
MutualFundHoldingData.prototype.lastPrice = undefined;

/**
 * Date for which last NAV is available.
 * @member {Object} lastPriceDate
 */
MutualFundHoldingData.prototype.lastPriceDate = undefined;

/**
 * Units pledged as collateral when applicable.
 * @member {Object} pledgedQuantity
 */
MutualFundHoldingData.prototype.pledgedQuantity = undefined;

