/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OrderMetadata model module.
 * @module model/OrderMetadata
 * @version v0
 */
export class OrderMetadata {
  /**
   * Constructs a new <code>OrderMetadata</code>.
   * @alias module:model/OrderMetadata
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderMetadata} obj Optional instance to populate.
   * @return {module:model/OrderMetadata} The populated <code>OrderMetadata</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderMetadata();
      if (data.hasOwnProperty('latency'))
        obj.latency = ApiClient.convertToType(data['latency'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} latency
 */
OrderMetadata.prototype.latency = undefined;

