/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.79
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PayoutModesData} from './PayoutModesData';

/**
 * The PayoutModesResponse model module.
 * @module model/PayoutModesResponse
 * @version v0
 */
export class PayoutModesResponse {
  /**
   * Constructs a new <code>PayoutModesResponse</code>.
   * @alias module:model/PayoutModesResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PayoutModesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PayoutModesResponse} obj Optional instance to populate.
   * @return {module:model/PayoutModesResponse} The populated <code>PayoutModesResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PayoutModesResponse();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], Object);
      if (data.hasOwnProperty('data'))
        obj.data = PayoutModesData.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {Object} status
 */
PayoutModesResponse.prototype.status = undefined;

/**
 * Available payout modes with eligibility details
 * @member {module:model/PayoutModesData} data
 */
PayoutModesResponse.prototype.data = undefined;

