/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.79
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PayoutDetails model module.
 * @module model/PayoutDetails
 * @version v0
 */
export class PayoutDetails {
  /**
   * Constructs a new <code>PayoutDetails</code>.
   * @alias module:model/PayoutDetails
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PayoutDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PayoutDetails} obj Optional instance to populate.
   * @return {module:model/PayoutDetails} The populated <code>PayoutDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PayoutDetails();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], Object);
      if (data.hasOwnProperty('mode'))
        obj.mode = ApiClient.convertToType(data['mode'], Object);
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], Object);
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], Object);
      if (data.hasOwnProperty('eta'))
        obj.eta = ApiClient.convertToType(data['eta'], Object);
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], Object);
      if (data.hasOwnProperty('transaction_id'))
        obj.transactionId = ApiClient.convertToType(data['transaction_id'], Object);
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], Object);
      if (data.hasOwnProperty('bank_name'))
        obj.bankName = ApiClient.convertToType(data['bank_name'], Object);
      if (data.hasOwnProperty('transaction_fee'))
        obj.transactionFee = ApiClient.convertToType(data['transaction_fee'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} status
 */
PayoutDetails.prototype.status = undefined;

/**
 * @member {Object} mode
 */
PayoutDetails.prototype.mode = undefined;

/**
 * @member {Object} amount
 */
PayoutDetails.prototype.amount = undefined;

/**
 * @member {Object} currency
 */
PayoutDetails.prototype.currency = undefined;

/**
 * @member {Object} eta
 */
PayoutDetails.prototype.eta = undefined;

/**
 * @member {Object} message
 */
PayoutDetails.prototype.message = undefined;

/**
 * @member {Object} transactionId
 */
PayoutDetails.prototype.transactionId = undefined;

/**
 * @member {Object} createdAt
 */
PayoutDetails.prototype.createdAt = undefined;

/**
 * @member {Object} bankName
 */
PayoutDetails.prototype.bankName = undefined;

/**
 * @member {Object} transactionFee
 */
PayoutDetails.prototype.transactionFee = undefined;

