/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SearchPage} from './SearchPage';

/**
 * The SearchMetaData model module.
 * @module model/SearchMetaData
 * @version v0
 */
export class SearchMetaData {
  /**
   * Constructs a new <code>SearchMetaData</code>.
   * @alias module:model/SearchMetaData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SearchMetaData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchMetaData} obj Optional instance to populate.
   * @return {module:model/SearchMetaData} The populated <code>SearchMetaData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchMetaData();
      if (data.hasOwnProperty('page'))
        obj.page = ApiClient.convertToType(data['page'], SearchPage);
    }
    return obj;
  }
}

/**
 * @member {module:model/SearchPage} page
 */
SearchMetaData.prototype.page = undefined;

