/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SearchPage model module.
 * @module model/SearchPage
 * @version v0
 */
export class SearchPage {
  /**
   * Constructs a new <code>SearchPage</code>.
   * @alias module:model/SearchPage
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SearchPage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchPage} obj Optional instance to populate.
   * @return {module:model/SearchPage} The populated <code>SearchPage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchPage();
      if (data.hasOwnProperty('page_number'))
        obj.pageNumber = ApiClient.convertToType(data['page_number'], 'Number');
      if (data.hasOwnProperty('total_pages'))
        obj.totalPages = ApiClient.convertToType(data['total_pages'], 'Number');
      if (data.hasOwnProperty('records'))
        obj.records = ApiClient.convertToType(data['records'], 'Number');
      if (data.hasOwnProperty('total_records'))
        obj.totalRecords = ApiClient.convertToType(data['total_records'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Object} pageNumber
 */
SearchPage.prototype.pageNumber = undefined;

/**
 * @member {Object} totalPages
 */
SearchPage.prototype.totalPages = undefined;

/**
 * @member {Object} records
 */
SearchPage.prototype.records = undefined;

/**
 * @member {Object} totalRecords
 */
SearchPage.prototype.totalRecords = undefined;

