/*
 * Upstox Developer API
 * Build your App on the Upstox platform  ![Banner](https://api-v2.upstox.com/api-docs/images/banner.jpg \"banner\")  # Introduction  Upstox API is a set of rest APIs that provide data required to build a complete investment and trading platform. Execute orders in real time, manage user portfolio, stream live market data (using Websocket), and more, with the easy to understand API collection.  All requests are over HTTPS and the requests are sent with the content-type ‘application/json’. Developers have the option of choosing the response type as JSON or CSV for a few API calls.  To be able to use these APIs you need to create an App in the Developer Console and generate your **apiKey** and **apiSecret**. You can use a redirect URL which will be called after the login flow.  If you are a **trader**, you can directly create apps from Upstox mobile app or the desktop platform itself from **Apps** sections inside the **Account** Tab. Head over to <a href=\"http://account.upstox.com/developer/apps\" target=\"_blank\">account.upstox.com/developer/apps</a>.</br> If you are a **business** looking to integrate Upstox APIs, reach out to us and we will get a custom app created for you in no time.  It is highly recommended that you do not embed the **apiSecret** in your frontend app. Create a remote backend which does the handshake on behalf of the frontend app. Marking the apiSecret in the frontend app will make your app vulnerable to threats and potential issues. 
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TradeWiseProfitAndLossData model module.
 * @module model/TradeWiseProfitAndLossData
 * @version v2
 */
export class TradeWiseProfitAndLossData {
  /**
   * Constructs a new <code>TradeWiseProfitAndLossData</code>.
   * Response data for trade wise data details
   * @alias module:model/TradeWiseProfitAndLossData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TradeWiseProfitAndLossData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TradeWiseProfitAndLossData} obj Optional instance to populate.
   * @return {module:model/TradeWiseProfitAndLossData} The populated <code>TradeWiseProfitAndLossData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TradeWiseProfitAndLossData();
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('isin'))
        obj.isin = ApiClient.convertToType(data['isin'], 'String');
      if (data.hasOwnProperty('scrip_name'))
        obj.scripName = ApiClient.convertToType(data['scrip_name'], 'String');
      if (data.hasOwnProperty('trade_type'))
        obj.tradeType = ApiClient.convertToType(data['trade_type'], 'String');
      if (data.hasOwnProperty('buy_date'))
        obj.buyDate = ApiClient.convertToType(data['buy_date'], 'String');
      if (data.hasOwnProperty('buy_average'))
        obj.buyAverage = ApiClient.convertToType(data['buy_average'], 'Number');
      if (data.hasOwnProperty('sell_date'))
        obj.sellDate = ApiClient.convertToType(data['sell_date'], 'String');
      if (data.hasOwnProperty('sell_average'))
        obj.sellAverage = ApiClient.convertToType(data['sell_average'], 'Number');
      if (data.hasOwnProperty('buy_amount'))
        obj.buyAmount = ApiClient.convertToType(data['buy_amount'], 'Number');
      if (data.hasOwnProperty('sell_amount'))
        obj.sellAmount = ApiClient.convertToType(data['sell_amount'], 'Number');
    }
    return obj;
  }
}

/**
 * The quantity of stock traded
 * @member {Number} quantity
 */
TradeWiseProfitAndLossData.prototype.quantity = undefined;

/**
 * ISIN of the stock
 * @member {String} isin
 */
TradeWiseProfitAndLossData.prototype.isin = undefined;

/**
 * Name of the scrip traded
 * @member {String} scripName
 */
TradeWiseProfitAndLossData.prototype.scripName = undefined;

/**
 * FUT - Futures   OPT - Options    EQ - Equity
 * @member {String} tradeType
 */
TradeWiseProfitAndLossData.prototype.tradeType = undefined;

/**
 * The date on which the stock was bought
 * @member {String} buyDate
 */
TradeWiseProfitAndLossData.prototype.buyDate = undefined;

/**
 * The average rate at which each quantity of the stock was bought
 * @member {Number} buyAverage
 */
TradeWiseProfitAndLossData.prototype.buyAverage = undefined;

/**
 * The date on which the stock was sold
 * @member {String} sellDate
 */
TradeWiseProfitAndLossData.prototype.sellDate = undefined;

/**
 * The average rate at which each quantity of the stock was sold
 * @member {Number} sellAverage
 */
TradeWiseProfitAndLossData.prototype.sellAverage = undefined;

/**
 * Total buy amount
 * @member {Number} buyAmount
 */
TradeWiseProfitAndLossData.prototype.buyAmount = undefined;

/**
 * Total sell amount
 * @member {Number} sellAmount
 */
TradeWiseProfitAndLossData.prototype.sellAmount = undefined;

