/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CashUnavailableToTrade} from './CashUnavailableToTrade';
import {PledgeUnavailableToTrade} from './PledgeUnavailableToTrade';

/**
 * The UnavailableToTrade model module.
 * @module model/UnavailableToTrade
 * @version v0
 */
export class UnavailableToTrade {
  /**
   * Constructs a new <code>UnavailableToTrade</code>.
   * @alias module:model/UnavailableToTrade
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UnavailableToTrade</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnavailableToTrade} obj Optional instance to populate.
   * @return {module:model/UnavailableToTrade} The populated <code>UnavailableToTrade</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UnavailableToTrade();
      if (data.hasOwnProperty('cash_unavailable_to_trade'))
        obj.cashUnavailableToTrade = CashUnavailableToTrade.constructFromObject(data['cash_unavailable_to_trade']);
      if (data.hasOwnProperty('pledge_unavailable_to_trade'))
        obj.pledgeUnavailableToTrade = PledgeUnavailableToTrade.constructFromObject(data['pledge_unavailable_to_trade']);
    }
    return obj;
  }
}

/**
 * @member {module:model/CashUnavailableToTrade} cashUnavailableToTrade
 */
UnavailableToTrade.prototype.cashUnavailableToTrade = undefined;

/**
 * @member {module:model/PledgeUnavailableToTrade} pledgeUnavailableToTrade
 */
UnavailableToTrade.prototype.pledgeUnavailableToTrade = undefined;

