/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UpdateUserIpRequest model module.
 * @module model/UpdateUserIpRequest
 * @version v0
 */
export default class UpdateUserIpRequest {
  /**
   * Constructs a new <code>UpdateUserIpRequest</code>.
   * @alias module:model/UpdateUserIpRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UpdateUserIpRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateUserIpRequest} obj Optional instance to populate.
   * @return {module:model/UpdateUserIpRequest} The populated <code>UpdateUserIpRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateUserIpRequest();
      if (data.hasOwnProperty('primary_ip'))
        obj.primaryIp = ApiClient.convertToType(data['primary_ip'], Object);
      if (data.hasOwnProperty('secondary_ip'))
        obj.secondaryIp = ApiClient.convertToType(data['secondary_ip'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} primaryIp
 */
UpdateUserIpRequest.prototype.primaryIp = undefined;

/**
 * @member {Object} secondaryIp
 */
UpdateUserIpRequest.prototype.secondaryIp = undefined;

