/*
 * Upstox Developer API
 * Build your App on the Upstox platform  ![Banner](https://api-v2.upstox.com/api-docs/images/banner.jpg \"banner\")  # Introduction  Upstox API is a set of rest APIs that provide data required to build a complete investment and trading platform. Execute orders in real time, manage user portfolio, stream live market data (using Websocket), and more, with the easy to understand API collection.  All requests are over HTTPS and the requests are sent with the content-type ‘application/json’. Developers have the option of choosing the response type as JSON or CSV for a few API calls.  To be able to use these APIs you need to create an App in the Developer Console and generate your **apiKey** and **apiSecret**. You can use a redirect URL which will be called after the login flow.  If you are a **trader**, you can directly create apps from Upstox mobile app or the desktop platform itself from **Apps** sections inside the **Account** Tab. Head over to <a href=\"http://account.upstox.com/developer/apps\" target=\"_blank\">account.upstox.com/developer/apps</a>.</br> If you are a **business** looking to integrate Upstox APIs, reach out to us and we will get a custom app created for you in no time.  It is highly recommended that you do not embed the **apiSecret** in your frontend app. Create a remote backend which does the handshake on behalf of the frontend app. Marking the apiSecret in the frontend app will make your app vulnerable to threats and potential issues. 
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {ApiGatewayErrorResponse} from '../model/ApiGatewayErrorResponse';
import {GetHistoricalCandleResponse} from '../model/GetHistoricalCandleResponse';
import {GetIntraDayCandleResponse} from '../model/GetIntraDayCandleResponse';

/**
* History service.
* @module api/HistoryApi
* @version v2
*/
export class HistoryApi {

    /**
    * Constructs a new HistoryApi. 
    * @alias module:api/HistoryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getHistoricalCandleData operation.
     * @callback moduleapi/HistoryApi~getHistoricalCandleDataCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetHistoricalCandleResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Historical candle data
     * Get OHLC values for all instruments across various timeframes. Historical data can be fetched for the following durations. 1minute: last 1 month candles till endDate 30minute: last 1 year candles till endDate day: last 1 year candles till endDate week: last 10 year candles till endDate month: last 10 year candles till endDate
     * @param {String} instrumentKey 
     * @param {String} interval 
     * @param {String} toDate 
     * @param {String} apiVersion API Version Header
     * @param {module:api/HistoryApi~getHistoricalCandleDataCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getHistoricalCandleData(instrumentKey, interval, toDate, apiVersion, callback) {
      
      let postBody = null;
      // verify the required parameter 'instrumentKey' is set
      if (instrumentKey === undefined || instrumentKey === null) {
        throw new Error("Missing the required parameter 'instrumentKey' when calling getHistoricalCandleData");
      }
      // verify the required parameter 'interval' is set
      if (interval === undefined || interval === null) {
        throw new Error("Missing the required parameter 'interval' when calling getHistoricalCandleData");
      }
      // verify the required parameter 'toDate' is set
      if (toDate === undefined || toDate === null) {
        throw new Error("Missing the required parameter 'toDate' when calling getHistoricalCandleData");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling getHistoricalCandleData");
      }

      let pathParams = {
        'instrumentKey': instrumentKey,'interval': interval,'to_date': toDate
      };
      let queryParams = {
        
      };
      let headerParams = {
        'Api-Version': apiVersion
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', '*/*'];
      let returnType = GetHistoricalCandleResponse;

      return this.apiClient.callApi(
        '/historical-candle/{instrumentKey}/{interval}/{to_date}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getHistoricalCandleData1 operation.
     * @callback moduleapi/HistoryApi~getHistoricalCandleData1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/GetHistoricalCandleResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Historical candle data
     * Get OHLC values for all instruments across various timeframes. Historical data can be fetched for the following durations. 1minute: last 1 month candles till endDate 30minute: last 1 year candles till endDate day: last 1 year candles till endDate week: last 10 year candles till endDate month: last 10 year candles till endDate
     * @param {String} instrumentKey 
     * @param {String} interval 
     * @param {String} toDate 
     * @param {String} fromDate 
     * @param {String} apiVersion API Version Header
     * @param {module:api/HistoryApi~getHistoricalCandleData1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getHistoricalCandleData1(instrumentKey, interval, toDate, fromDate, apiVersion, callback) {
      
      let postBody = null;
      // verify the required parameter 'instrumentKey' is set
      if (instrumentKey === undefined || instrumentKey === null) {
        throw new Error("Missing the required parameter 'instrumentKey' when calling getHistoricalCandleData1");
      }
      // verify the required parameter 'interval' is set
      if (interval === undefined || interval === null) {
        throw new Error("Missing the required parameter 'interval' when calling getHistoricalCandleData1");
      }
      // verify the required parameter 'toDate' is set
      if (toDate === undefined || toDate === null) {
        throw new Error("Missing the required parameter 'toDate' when calling getHistoricalCandleData1");
      }
      // verify the required parameter 'fromDate' is set
      if (fromDate === undefined || fromDate === null) {
        throw new Error("Missing the required parameter 'fromDate' when calling getHistoricalCandleData1");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling getHistoricalCandleData1");
      }

      let pathParams = {
        'instrumentKey': instrumentKey,'interval': interval,'to_date': toDate,'from_date': fromDate
      };
      let queryParams = {
        
      };
      let headerParams = {
        'Api-Version': apiVersion
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', '*/*'];
      let returnType = GetHistoricalCandleResponse;

      return this.apiClient.callApi(
        '/historical-candle/{instrumentKey}/{interval}/{to_date}/{from_date}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getIntraDayCandleData operation.
     * @callback moduleapi/HistoryApi~getIntraDayCandleDataCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetIntraDayCandleResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Intra day candle data
     * Get OHLC values for all instruments for the present trading day
     * @param {String} instrumentKey 
     * @param {String} interval 
     * @param {String} apiVersion API Version Header
     * @param {module:api/HistoryApi~getIntraDayCandleDataCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getIntraDayCandleData(instrumentKey, interval, apiVersion, callback) {
      
      let postBody = null;
      // verify the required parameter 'instrumentKey' is set
      if (instrumentKey === undefined || instrumentKey === null) {
        throw new Error("Missing the required parameter 'instrumentKey' when calling getIntraDayCandleData");
      }
      // verify the required parameter 'interval' is set
      if (interval === undefined || interval === null) {
        throw new Error("Missing the required parameter 'interval' when calling getIntraDayCandleData");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling getIntraDayCandleData");
      }

      let pathParams = {
        'instrumentKey': instrumentKey,'interval': interval
      };
      let queryParams = {
        
      };
      let headerParams = {
        'Api-Version': apiVersion
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', '*/*'];
      let returnType = GetIntraDayCandleResponse;

      return this.apiClient.callApi(
        '/historical-candle/intraday/{instrumentKey}/{interval}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}