/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpstoxClient);
  }
}(this, function(expect, UpstoxClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CancelOrExitMultiOrderData', function() {
      beforeEach(function() {
        instance = new UpstoxClient.CancelOrExitMultiOrderData();
      });

      it('should create an instance of CancelOrExitMultiOrderData', function() {
        // TODO: update the code to test CancelOrExitMultiOrderData
        expect(instance).to.be.a(UpstoxClient.CancelOrExitMultiOrderData);
      });

      it('should have the property orderIds (base name: "order_ids")', function() {
        // TODO: update the code to test the property orderIds
        expect(instance).to.have.property('orderIds');
        // expect(instance.orderIds).to.be(expectedValueLiteral);
      });

    });
  });

}));
