/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.82
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpstoxClient);
  }
}(this, function(expect, UpstoxClient) {
  'use strict';

  var instance;

  var samplePayload = {
    status: 'success',
    data: {
      'NSE_EQ:TECHM': {
        instrument_token: 'NSE_EQ|INE669E01016',
        symbol: 'TECHM',
        last_price: 104.1,
        cas_eligible: false
      }
    }
  };

  describe('(package)', function() {
    describe('GetFullMarketQuoteResponseV3', function() {
      beforeEach(function() {
        instance = new UpstoxClient.GetFullMarketQuoteResponseV3();
      });

      it('should create an instance of GetFullMarketQuoteResponseV3', function() {
        expect(instance).to.be.a(UpstoxClient.GetFullMarketQuoteResponseV3);
      });

      it('should have the property status (base name: "status")', function() {
        expect(instance).to.have.property('status');
      });

      it('should have the property data (base name: "data")', function() {
        expect(instance).to.have.property('data');
      });

      it('should expose the StatusEnum values', function() {
        expect(UpstoxClient.GetFullMarketQuoteResponseV3.StatusEnum.success).to.be('success');
        expect(UpstoxClient.GetFullMarketQuoteResponseV3.StatusEnum.error).to.be('error');
        expect(UpstoxClient.GetFullMarketQuoteResponseV3.StatusEnum.partialSuccess).to.be('partial_success');
      });

      describe('constructFromObject', function() {
        var parsed;

        beforeEach(function() {
          parsed = UpstoxClient.GetFullMarketQuoteResponseV3.constructFromObject(samplePayload);
        });

        // Guards against the swagger-codegen 3.0.82 OpenAPI 3.1 regression that
        // emitted `Object` for both properties on this model.
        it('should deserialize status as a String', function() {
          expect(parsed.status).to.be.a('string');
          expect(parsed.status).to.be('success');
        });

        it('should deserialize data as a map of MarketQuoteSymbolV3', function() {
          expect(parsed.data).to.be.an('object');
          expect(parsed.data).to.have.property('NSE_EQ:TECHM');

          var symbol = parsed.data['NSE_EQ:TECHM'];
          expect(symbol).to.be.a(UpstoxClient.MarketQuoteSymbolV3);
          expect(symbol.instrumentToken).to.be('NSE_EQ|INE669E01016');
          expect(symbol.lastPrice).to.be.a('number');
          expect(symbol.casEligible).to.be(false);
        });
      });
    });
  });

}));
