/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpstoxClient);
  }
}(this, function(expect, UpstoxClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MarginData', function() {
      beforeEach(function() {
        instance = new UpstoxClient.MarginData();
      });

      it('should create an instance of MarginData', function() {
        // TODO: update the code to test MarginData
        expect(instance).to.be.a(UpstoxClient.MarginData);
      });

      it('should have the property margins (base name: "margins")', function() {
        // TODO: update the code to test the property margins
        expect(instance).to.have.property('margins');
        // expect(instance.margins).to.be(expectedValueLiteral);
      });

      it('should have the property requiredMargin (base name: "required_margin")', function() {
        // TODO: update the code to test the property requiredMargin
        expect(instance).to.have.property('requiredMargin');
        // expect(instance.requiredMargin).to.be(expectedValueLiteral);
      });

      it('should have the property finalMargin (base name: "final_margin")', function() {
        // TODO: update the code to test the property finalMargin
        expect(instance).to.have.property('finalMargin');
        // expect(instance.finalMargin).to.be(expectedValueLiteral);
      });

    });
  });

}));
