/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.82
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpstoxClient);
  }
}(this, function(expect, UpstoxClient) {
  'use strict';

  var instance;

  // A representative payload for a single instrument as returned by
  // GET /v3/market-quote/quotes.
  var samplePayload = {
    ohlc: { open: 100.5, high: 105.25, low: 99.75, close: 104.1, volume: 12345 },
    depth: { buy: [], sell: [] },
    timestamp: '2026-09-05T10:15:30.000Z',
    instrument_token: 'NSE_EQ|INE669E01016',
    symbol: 'TECHM',
    last_price: 104.1,
    volume: 12345,
    average_price: 102.3,
    oi: 4500,
    net_change: 3.6,
    total_buy_quantity: 1500,
    total_sell_quantity: 1800,
    lower_circuit_limit: 90.0,
    upper_circuit_limit: 115.0,
    last_trade_time: '2026-09-05T10:15:29.000Z',
    oi_day_high: 5200,
    oi_day_low: 4100,
    prev_close_price: 100.5,
    year_high: 130.0,
    year_low: 85.0,
    previous_oi: 4400,
    indicative_equilibrium_price: 103.5,
    reference_price: 100.5,
    indicative_equilibrium_quantity: 700,
    indicative_imbalance_quantity_total: 250,
    indicative_imbalance_quantity_market: 120,
    cas_eligible: true
  };

  describe('(package)', function() {
    describe('MarketQuoteSymbolV3', function() {
      beforeEach(function() {
        instance = new UpstoxClient.MarketQuoteSymbolV3();
      });

      it('should create an instance of MarketQuoteSymbolV3', function() {
        expect(instance).to.be.a(UpstoxClient.MarketQuoteSymbolV3);
      });

      var properties = [
        'ohlc', 'depth', 'timestamp', 'instrumentToken', 'symbol', 'lastPrice',
        'volume', 'averagePrice', 'oi', 'netChange', 'totalBuyQuantity',
        'totalSellQuantity', 'lowerCircuitLimit', 'upperCircuitLimit',
        'lastTradeTime', 'oiDayHigh', 'oiDayLow', 'prevClosePrice', 'yearHigh',
        'yearLow', 'previousOi', 'indicativeEquilibriumPrice', 'referencePrice',
        'indicativeEquilibriumQuantity', 'indicativeImbalanceQuantityTotal',
        'indicativeImbalanceQuantityMarket', 'casEligible'
      ];

      properties.forEach(function(property) {
        it('should have the property ' + property, function() {
          expect(instance).to.have.property(property);
        });
      });

      describe('constructFromObject', function() {
        var parsed;

        beforeEach(function() {
          parsed = UpstoxClient.MarketQuoteSymbolV3.constructFromObject(samplePayload);
        });

        it('should map snake_case payload keys onto camelCase properties', function() {
          expect(parsed.instrumentToken).to.be('NSE_EQ|INE669E01016');
          expect(parsed.symbol).to.be('TECHM');
          expect(parsed.lastPrice).to.be(104.1);
          expect(parsed.prevClosePrice).to.be(100.5);
          expect(parsed.indicativeImbalanceQuantityMarket).to.be(120);
        });

        // Guards against the swagger-codegen 3.0.82 OpenAPI 3.1 regression that
        // emitted `Object` for every primitive on this model.
        it('should deserialize string fields as String', function() {
          ['timestamp', 'instrumentToken', 'symbol', 'lastTradeTime'].forEach(function(property) {
            expect(parsed[property]).to.be.a('string');
          });
        });

        it('should deserialize numeric fields as Number', function() {
          [
            'lastPrice', 'averagePrice', 'oi', 'netChange', 'totalBuyQuantity',
            'totalSellQuantity', 'lowerCircuitLimit', 'upperCircuitLimit',
            'oiDayHigh', 'oiDayLow', 'prevClosePrice', 'yearHigh', 'yearLow',
            'previousOi', 'indicativeEquilibriumPrice', 'referencePrice',
            'volume', 'indicativeEquilibriumQuantity',
            'indicativeImbalanceQuantityTotal', 'indicativeImbalanceQuantityMarket'
          ].forEach(function(property) {
            expect(parsed[property]).to.be.a('number');
          });
        });

        it('should deserialize casEligible as Boolean', function() {
          expect(parsed.casEligible).to.be.a('boolean');
          expect(parsed.casEligible).to.be(true);
        });

        // The declared types must actually coerce. A model typed `Object` would
        // pass these values straight through and leave them as strings.
        it('should coerce string-encoded primitives to their declared types', function() {
          var coerced = UpstoxClient.MarketQuoteSymbolV3.constructFromObject({
            last_price: '104.1',
            oi: '4500',
            year_high: '130.0',
            cas_eligible: 'true'
          });

          expect(coerced.lastPrice).to.be(104.1);
          expect(coerced.oi).to.be(4500);
          expect(coerced.yearHigh).to.be(130.0);
          expect(coerced.casEligible).to.be(true);
        });

        it('should deserialize ohlc as an OhlcV3 instance', function() {
          expect(parsed.ohlc).to.be.a(UpstoxClient.OhlcV3);
        });

        it('should deserialize depth as a DepthMap instance', function() {
          expect(parsed.depth).to.be.a(UpstoxClient.DepthMap);
        });
      });
    });
  });

}));
