/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpstoxClient);
  }
}(this, function(expect, UpstoxClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UpstoxClient.MarketHolidaysAndTimingsApi();
  });

  describe('(package)', function() {
    describe('MarketHolidaysAndTimingsApi', function() {
      describe('getExchangeTimings', function() {
        it('should call getExchangeTimings successfully', function(done) {
          // TODO: uncomment, update parameter values for getExchangeTimings call and complete the assertions
          /*

          instance.getExchangeTimings(_date, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UpstoxClient.GetExchangeTimingResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getHoliday', function() {
        it('should call getHoliday successfully', function(done) {
          // TODO: uncomment, update parameter values for getHoliday call and complete the assertions
          /*

          instance.getHoliday(_date, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UpstoxClient.GetHolidayResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getHolidays', function() {
        it('should call getHolidays successfully', function(done) {
          // TODO: uncomment getHolidays call and complete the assertions
          /*

          instance.getHolidays(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UpstoxClient.GetHolidayResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getMarketStatus', function() {
        it('should call getMarketStatus successfully', function(done) {
          // TODO: uncomment, update parameter values for getMarketStatus call and complete the assertions
          /*

          instance.getMarketStatus(exchange, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UpstoxClient.GetMarketStatusResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
